### ISSUE TITLE
Terraform errors

### ISSUE THREAD

**Issue by ChadOhman** [digitalocean/mastodon-on-kubernetes#4]
Instance admin for Mastodon Canada (mstdn.ca) here, experimenting with this in a dev environment...

It seems there's an issue with Spaces being in a different region. I use TOR1, but the nearest geographical datacenter with Spaces is NYC3.

After `terraform apply "tf-mastodon.out"` I get:
`╷
│ Error: Error creating DatabaseFirewall: PUT https://api.digitalocean.com/v2/databases/f800f438-476e-4566-9093-8a5841ffb0fd/firewall: 422 (request "9c6f185c-89de-4381-a32b-064c364adf51") no VMs found for Kubernetes cluster
│
│   with digitalocean_database_firewall.mastodon_pg_firewall[0],
│   on digitalocean-managed-postgres.tf line 33, in resource "digitalocean_database_firewall" "mastodon_pg_firewall":
│   33: resource "digitalocean_database_firewall" "mastodon_pg_firewall" {
│
╵
╷
│ Error: Error creating Spaces bucket: BucketAlreadyExists: Bucket already exists
│       status code: 409, request id: , host id:
│
│   with digitalocean_spaces_bucket.mastodon_spaces[0],
│   on digitalocean-s3.tf line 1, in resource "digitalocean_spaces_bucket" "mastodon_spaces":
│    1: resource "digitalocean_spaces_bucket" "mastodon_spaces" {
│
╵
`

Attaching my `mastodon.tfvars` if it helps. Otherwise, I haven't changed anything else.
[mastodon.tfvars.txt](https://github.com/digitalocean/mastodon-on-kubernetes/files/10419633/mastodon.tfvars.txt)

**Comment by ChadOhman** [comment]
Hello,

After chatting with Elan, it turns out Spaces names must be unique. With this fixed, I'm still getting the following errors:
![image](https://user-images.githubusercontent.com/2351/212563395-d45cf63c-8d83-4ed5-bd5b-7c723e2ea8a2.png)

Thanks

**Comment by diabhey** [comment]
@ChadOhman 
- Kudos to you for maintaining `mstdn.ca`!
- Yes, the spaces name must be unique, and I am glad it was sorted out
- Thanks for raising the terraform issue. I have added the fix, and the changes have been merged to `main.` 

Let us know in case of any other questions. Happy Mastodoning!
